/*
 * SPDX-FileCopyrightText: 2020, microG Project Team
 * SPDX-License-Identifier: Apache-2.0
 */

apply plugin: 'com.squareup.wire'
apply plugin: 'kotlin'

dependencies {
    implementation "com.squareup.wire:wire-runtime:$wireVersion"
}

wire {
    kotlin {
        javaInterop = true
    }
}

sourceSets {
    main.java.srcDirs += "$buildDir/generated/source/wire"
}

compileJava {
    sourceCompatibility = rootProject.ext.javaVersion
    targetCompatibility = rootProject.ext.javaVersion
}

compileKotlin {
    kotlinOptions.jvmTarget = rootProject.ext.javaVersion.toString()
}

compileTestKotlin {
    kotlinOptions.jvmTarget = rootProject.ext.javaVersion.toString()
}
